version: '3.8'

services:
  db:
    image: postgres:15
    container_name: mydb
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      # Persistencia de datos
      - ./db/data:/var/lib/postgresql/data
      # Inicialización automática de tablas
      - ./db/schema/schema.sql:/docker-entrypoint-initdb.d/schema.sql
